/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recepcija.view;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import recepcija.controller.ObradaPosjeta;
import recepcija.util.ZavrsniUtil;

/**
 *
 * @author Igor
 */
public class RezervacijeProzor extends javax.swing.JFrame {

    /**
     * Creates new form RezervacijeProzor
     */
    private ObradaPosjeta op;
    private Date datum;
    private Calendar c;

    public RezervacijeProzor() {
        initComponents();
        setTitle(ZavrsniUtil.getNaslov("Rezervacije"));
        op = new ObradaPosjeta();
        c = Calendar.getInstance();
        dpDatumRezervacije.setDate(LocalDate.now().minusDays(1));
        btnTrazi.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRezervacije = new javax.swing.JTable();
        dpDatumRezervacije = new com.github.lgooddatepicker.components.DatePicker();
        btnTrazi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnToExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Šifra", "Korisnik", "Odjava", "Osobe", "Sobe"
            }
        ));
        jScrollPane1.setViewportView(tblRezervacije);

        btnTrazi.setText("Traži");
        btnTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraziActionPerformed(evt);
            }
        });

        jLabel1.setText("Traži po datumu");

        btnToExcel.setText("To Excel");
        btnToExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dpDatumRezervacije, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnTrazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnToExcel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dpDatumRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrazi)
                    .addComponent(btnToExcel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraziActionPerformed
        if (dpDatumRezervacije.getDate() == null) {
            return;
        }
        datum = Date.from(dpDatumRezervacije.getDate().atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());
        TablicaModelRezervacije m = new TablicaModelRezervacije(op.readPrijava(datum));
        tblRezervacije.setModel(m);
    }//GEN-LAST:event_btnTraziActionPerformed

    private void btnToExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToExcelActionPerformed
        if (tblRezervacije.getModel() == null || tblRezervacije.getRowCount() == 0) {
            return;
        }
        c.setTime(datum);
        JFileChooser jfc = new JFileChooser();
        jfc.setCurrentDirectory(new File(System.getProperty("user.home")));
        jfc.setSelectedFile(new File(System.getProperty("user.home")
                + File.separator + "Rezervacije_" + c.get(Calendar.DAY_OF_MONTH) + "_" + (c.get(Calendar.MONTH) + 1) + "_" + c.get(Calendar.YEAR) + ".xlsx"));
        if (jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                TableModel m = tblRezervacije.getModel();
                BufferedWriter writer = new BufferedWriter(
                        new FileWriter(jfc.getSelectedFile(), StandardCharsets.UTF_8));
                for (int i = 0; i < m.getColumnCount(); i++) {
                    writer.write(m.getColumnName(i) + "\t");
                }
                writer.write("\n");
                for (int i = 0; i < m.getRowCount(); i++) {
                    for (int j = 0; j < m.getColumnCount(); j++) {
                        writer.write(m.getValueAt(i, j).toString() + "\t");
                    }
                    writer.write("\n");
                }
                writer.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(getRootPane(), e.getStackTrace());
            }
        }

    }//GEN-LAST:event_btnToExcelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnToExcel;
    private javax.swing.JButton btnTrazi;
    private com.github.lgooddatepicker.components.DatePicker dpDatumRezervacije;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRezervacije;
    // End of variables declaration//GEN-END:variables
}
