/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zavrsni.view;

import javax.swing.JOptionPane;
import org.hibernate.Session;
import zavrsni.util.HibernateUtil;

/**
 *
 * @author Igor
 */
public class SplashScreen extends javax.swing.JFrame {
    private int a;
    private boolean b;
    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        postavke();
    }
    private void postavke(){
        a = 1;
        b = false;
        Ucitanje ucitanje = new Ucitanje();
        ucitanje.start();
        UcitanjeDva ucitanjeDva = new UcitanjeDva();
        ucitanjeDva.start();
    }
    
    private class Ucitanje extends Thread{

        @Override
        public void run() {
            Session s = HibernateUtil.getSession();
            if(!s.getMetamodel().getEntities().isEmpty()){
                b = true;
                for(int i = a;i < 100;i++){
                    try {
                        pbLoad.setValue(a++);
                        Thread.sleep(3);
                    } catch (InterruptedException ex) {
                    }
                }
                
                new Autorizacija().setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(getRootPane(), "Problem kod povezivanja na bazu");
            }
         }
        
    }
    
    private class UcitanjeDva extends Thread{

        @Override
        public void run() {
            if(b){
                return;
            }
            try {
                pbLoad.setValue(a++);
                Thread.sleep(1000);
                run();
            } catch (InterruptedException ex) {
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbLoad = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pbLoad, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 281, Short.MAX_VALUE)
                .addComponent(pbLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar pbLoad;
    // End of variables declaration//GEN-END:variables
}
